#server:
  #port: 7070
#myCustomEnvs:
  #devName: Camilla Conte

---
server:
  port: 4500
myCustomEnvs:
  devName: Camilla Conte
  autocode: xyz458

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 7070
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000
