#server:
  #port: 7070
#myCustomEnvs:
  #devName: Camilla Conte

---
server:
  port: 4500
myCustomEnvs:
  devName: Camilla Conte
  autocode: xyz458

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 7070
customProdVar:
  welcomeMsg: Hello from prod
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000
customTestVar:
  welcomeMsg: Hello from test

